/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface DB_account {
  'account_id': Buffer;
  'account_type'?: DB_MidenAccountType | null;
  'block_hash': Buffer;
  'block_number': bigint;
  'block_updated_account_index': number;
  'code_procedure'?: string[] | null;
  'is_faucet'?: boolean | null;
  'is_private': boolean;
}
export interface DB_account_update {
  'account_id': Buffer;
  'account_update_id': string;
  'block_hash': Buffer;
  'block_number': bigint;
  'block_updated_account_index': number;
  'nonce'?: bigint | null;
  'state_hash': Buffer;
}
export interface DB_account_vault_asset {
  'account_id': Buffer;
  'account_vault_asset_id': string;
  'amount': bigint;
  'faucet_id': Buffer;
}
export interface DB_block {
  'account_root': Buffer;
  'block_hash': Buffer;
  'block_number': bigint;
  'chain_root': Buffer;
  'note_root': Buffer;
  'nullifier_root': Buffer;
  'number_of_transactions': bigint;
  'proof_hash': Buffer;
  'sub_hash': Buffer;
  'timestamp': bigint;
  'tx_hash': Buffer;
  'version': bigint;
}
export interface DB_note {
  'block_batch_index': bigint;
  'block_hash': Buffer;
  'block_note_index_in_batch': bigint;
  'block_number': bigint;
  'inputs'?: any | null;
  'note_aux': bigint;
  'note_id': Buffer;
  'note_tag': bigint;
  'note_type': DB_MidenNoteType;
  'nullifier'?: Buffer | null;
  'recipient'?: Buffer | null;
  'script_code'?: string | null;
  'sender': Buffer;
}
export interface DB_note_asset {
  'amount': bigint;
  'faucet_id': Buffer;
  'note_asset_id': string;
  'note_id': Buffer;
}
export interface DB_nullifier {
  'block_created_nullifier_index': number;
  'block_hash': Buffer;
  'block_number': bigint;
  'nullifier': Buffer;
}
export interface DB_ref {
  'block_hash': Buffer;
  'block_number': number;
  'id': number;
}
export interface DB_transaction {
  'account_id': Buffer;
  'block_hash': Buffer;
  'block_number': bigint;
  'block_updated_account_transaction_index': number;
  'transaction_id': Buffer;
}
export enum DB_MidenNoteType {
  'Private' = 'Private',
  'Encrypted' = 'Encrypted',
  'Public' = 'Public',
}
export enum DB_MidenAccountType {
  'FungibleFaucet' = 'FungibleFaucet',
  'NonFungibleFaucet' = 'NonFungibleFaucet',
  'RegularAccountImmutableCode' = 'RegularAccountImmutableCode',
  'RegularAccountUpdatableCode' = 'RegularAccountUpdatableCode',
}
/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface DB_READ_account {
  'account_id': Buffer;
  'account_type': DB_MidenAccountType | null;
  'block_hash': Buffer;
  'block_number': bigint;
  'block_updated_account_index': number;
  'code_procedure': string[] | null;
  'is_faucet': boolean | null;
  'is_private': boolean;
}
export interface DB_READ_account_update {
  'account_id': Buffer;
  'account_update_id': string;
  'block_hash': Buffer;
  'block_number': bigint;
  'block_updated_account_index': number;
  'nonce': bigint | null;
  'state_hash': Buffer;
}
export interface DB_READ_account_vault_asset {
  'account_id': Buffer;
  'account_vault_asset_id': string;
  'amount': bigint;
  'faucet_id': Buffer;
}
export interface DB_READ_block {
  'account_root': Buffer;
  'block_hash': Buffer;
  'block_number': bigint;
  'chain_root': Buffer;
  'note_root': Buffer;
  'nullifier_root': Buffer;
  'number_of_transactions': bigint;
  'proof_hash': Buffer;
  'sub_hash': Buffer;
  'timestamp': bigint;
  'tx_hash': Buffer;
  'version': bigint;
}
export interface DB_READ_note {
  'block_batch_index': bigint;
  'block_hash': Buffer;
  'block_note_index_in_batch': bigint;
  'block_number': bigint;
  'inputs': any | null;
  'note_aux': bigint;
  'note_id': Buffer;
  'note_tag': bigint;
  'note_type': DB_MidenNoteType;
  'nullifier': Buffer | null;
  'recipient': Buffer | null;
  'script_code': string | null;
  'sender': Buffer;
}
export interface DB_READ_note_asset {
  'amount': bigint;
  'faucet_id': Buffer;
  'note_asset_id': string;
  'note_id': Buffer;
}
export interface DB_READ_nullifier {
  'block_created_nullifier_index': number;
  'block_hash': Buffer;
  'block_number': bigint;
  'nullifier': Buffer;
}
export interface DB_READ_ref {
  'block_hash': Buffer;
  'block_number': number;
  'id': number;
}
export interface DB_READ_transaction {
  'account_id': Buffer;
  'block_hash': Buffer;
  'block_number': bigint;
  'block_updated_account_transaction_index': number;
  'transaction_id': Buffer;
}
/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface DB_UPDATE_account {
  'account_id'?: Buffer;
  'account_type'?: DB_MidenAccountType | null;
  'block_hash'?: Buffer;
  'block_number'?: bigint;
  'block_updated_account_index'?: number;
  'code_procedure'?: string[] | null;
  'is_faucet'?: boolean | null;
  'is_private'?: boolean;
}
export interface DB_UPDATE_account_update {
  'account_id'?: Buffer;
  'account_update_id'?: string;
  'block_hash'?: Buffer;
  'block_number'?: bigint;
  'block_updated_account_index'?: number;
  'nonce'?: bigint | null;
  'state_hash'?: Buffer;
}
export interface DB_UPDATE_account_vault_asset {
  'account_id'?: Buffer;
  'account_vault_asset_id'?: string;
  'amount'?: bigint;
  'faucet_id'?: Buffer;
}
export interface DB_UPDATE_block {
  'account_root'?: Buffer;
  'block_hash'?: Buffer;
  'block_number'?: bigint;
  'chain_root'?: Buffer;
  'note_root'?: Buffer;
  'nullifier_root'?: Buffer;
  'number_of_transactions'?: bigint;
  'proof_hash'?: Buffer;
  'sub_hash'?: Buffer;
  'timestamp'?: bigint;
  'tx_hash'?: Buffer;
  'version'?: bigint;
}
export interface DB_UPDATE_note {
  'block_batch_index'?: bigint;
  'block_hash'?: Buffer;
  'block_note_index_in_batch'?: bigint;
  'block_number'?: bigint;
  'inputs'?: any | null;
  'note_aux'?: bigint;
  'note_id'?: Buffer;
  'note_tag'?: bigint;
  'note_type'?: DB_MidenNoteType;
  'nullifier'?: Buffer | null;
  'recipient'?: Buffer | null;
  'script_code'?: string | null;
  'sender'?: Buffer;
}
export interface DB_UPDATE_note_asset {
  'amount'?: bigint;
  'faucet_id'?: Buffer;
  'note_asset_id'?: string;
  'note_id'?: Buffer;
}
export interface DB_UPDATE_nullifier {
  'block_created_nullifier_index'?: number;
  'block_hash'?: Buffer;
  'block_number'?: bigint;
  'nullifier'?: Buffer;
}
export interface DB_UPDATE_ref {
  'block_hash'?: Buffer;
  'block_number'?: number;
  'id'?: number;
}
export interface DB_UPDATE_transaction {
  'account_id'?: Buffer;
  'block_hash'?: Buffer;
  'block_number'?: bigint;
  'block_updated_account_transaction_index'?: number;
  'transaction_id'?: Buffer;
}
