FROM --platform=linux/amd64 rust:1.80-slim-bookworm AS builder

RUN apt-get update && \
  apt-get -y upgrade && \
  rustup target add x86_64-unknown-linux-gnu

COPY ./ ./
RUN cargo build --release --target=x86_64-unknown-linux-gnu

CMD ["./target/x86_64-unknown-linux-gnu/release/midenscan-indexer"]
